# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 08:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('content', models.TextField(db_index=True, verbose_name='content')),
                ('html', models.TextField(editable=False, verbose_name='html')),
                ('is_private', models.BooleanField(default=False, verbose_name='is private')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'answers',
                'db_table': 'answer',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('html', models.TextField(editable=False, verbose_name='html')),
                ('quote', models.TextField(verbose_name='quote')),
                ('is_private', models.BooleanField(default=False, verbose_name='is private')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'chapter',
                'verbose_name_plural': 'chapters',
                'db_table': 'chapter',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tutorial.Topic')),
            ],
            options={
                'verbose_name': 'topic',
                'verbose_name_plural': 'topics',
                'db_table': 'topic',
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('content', models.TextField(db_index=True, verbose_name='content')),
                ('answer', models.TextField(verbose_name='answer')),
                ('html', models.TextField(editable=False, verbose_name='html')),
                ('is_private', models.BooleanField(default=False, verbose_name='is private')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains', to='tutorial.Chapter', verbose_name='chapter')),
            ],
            options={
                'verbose_name': 'train',
                'verbose_name_plural': 'trains',
                'db_table': 'train',
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('is_private', models.BooleanField(default=False, verbose_name='is private')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='tutorial.Topic', verbose_name='topic')),
            ],
            options={
                'verbose_name': 'tutorial',
                'verbose_name_plural': 'tutorials',
                'db_table': 'tutorial',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='tutorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='tutorial.Tutorial', verbose_name='tutorial'),
        ),
        migrations.AddField(
            model_name='answer',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tutorial.Train', verbose_name='train'),
        ),
        migrations.AddIndex(
            model_name='tutorial',
            index=models.Index(fields=['title'], name='idx_title'),
        ),
    ]
